'use client';

import { useState } from 'react';
import CopyButton from './CopyButton';

interface CodeGeneratorProps {
  clientId: string;
}

export default function CodeGenerator({ clientId }: CodeGeneratorProps) {
  const [showInstructions, setShowInstructions] = useState(false);

  const generateServerCode = () => {
    return `// Standalone LinkedIn Webhook Server
// Generated by HookedIn - https://linkedin-hookedin.vercel.app
// This server handles LinkedIn webhook challenges and event notifications

const express = require('express');
const crypto = require('crypto');

// =============================================================================
// CONFIGURATION
// =============================================================================

// Option 1: Use environment variables (RECOMMENDED for production)
const CLIENT_ID = process.env.LINKEDIN_CLIENT_ID || '${clientId}';
const CLIENT_SECRET = process.env.LINKEDIN_CLIENT_SECRET || 'your-client-secret-here';
const PORT = process.env.PORT || 3000;

// Option 2: Hardcode values (ONLY for local testing - NOT recommended for production)
// Uncomment and replace with your actual credentials if testing locally:
// const CLIENT_ID = '${clientId}'; // Replace if different
// const CLIENT_SECRET = 'WPL_AP1.xxxxxxxxxxxxx'; // Replace with your actual secret

// =============================================================================
// EXPRESS APP SETUP
// =============================================================================

const app = express();

// Important: Parse raw body as text for signature validation
// DO NOT use express.json() as it will parse the body and break signature validation
app.use(express.text({ type: '*/*' }));

// =============================================================================
// WEBHOOK ENDPOINTS
// =============================================================================

/**
 * GET /webhook - Handle LinkedIn challenge validation
 *
 * LinkedIn sends a challenge request when you first configure your webhook.
 * This endpoint computes the correct response to validate your webhook.
 */
app.get('/webhook', (req, res) => {
  try {
    const { challengeCode } = req.query;

    // If no challenge code, just return status
    if (!challengeCode) {
      return res.json({
        status: 'Webhook endpoint active',
        message: 'Ready to receive LinkedIn webhook events'
      });
    }

    // Compute challenge response using HMAC-SHA256
    const hmac = crypto.createHmac('sha256', CLIENT_SECRET);
    hmac.update(challengeCode);
    const challengeResponse = hmac.digest('hex');

    console.log('✅ Challenge received and validated');
    console.log('   Challenge Code:', challengeCode);
    console.log('   Challenge Response:', challengeResponse);

    // Return the challenge response to LinkedIn
    res.json({ challengeCode, challengeResponse });

  } catch (error) {
    console.error('❌ Error handling challenge:', error.message);
    res.status(500).json({
      error: 'Internal server error',
      message: error.message
    });
  }
});

/**
 * POST /webhook - Handle LinkedIn event notifications
 *
 * This endpoint receives actual webhook events from LinkedIn.
 * It validates the signature and logs the event payload.
 */
app.post('/webhook', (req, res) => {
  try {
    // Extract signature from headers
    const signature = req.headers['x-li-signature'];
    const payload = req.body;

    console.log('📨 Event received from LinkedIn');

    // Validate signature to ensure the event is from LinkedIn
    const isValid = validateLinkedInSignature(payload, signature, CLIENT_SECRET);

    if (!isValid) {
      console.error('❌ Invalid signature - rejecting event');
      console.error('   Received signature:', signature);
      return res.status(401).json({
        error: 'Invalid signature',
        message: 'The event signature does not match. Event may not be from LinkedIn.'
      });
    }

    console.log('✅ Signature validated successfully');

    // Parse the event payload
    let event;
    try {
      event = JSON.parse(payload);
    } catch (parseError) {
      console.error('❌ Failed to parse event payload:', parseError.message);
      return res.status(400).json({
        error: 'Invalid JSON payload'
      });
    }

    // Log the event (in production, you'd save this to a database)
    console.log('📋 Event Details:');
    console.log(JSON.stringify(event, null, 2));

    // Extract common event fields
    if (event.eventType) {
      console.log('   Event Type:', event.eventType);
    }
    if (event.eventTimestamp) {
      console.log('   Event Timestamp:', new Date(event.eventTimestamp).toISOString());
    }

    // Respond to LinkedIn with success
    res.json({
      success: true,
      message: 'Event received and processed successfully'
    });

  } catch (error) {
    console.error('❌ Error processing event:', error.message);
    res.status(500).json({
      error: 'Internal server error',
      message: error.message
    });
  }
});

// =============================================================================
// SIGNATURE VALIDATION FUNCTION
// =============================================================================

/**
 * Validates LinkedIn webhook signature
 *
 * IMPORTANT: LinkedIn's documentation has an error!
 * LinkedIn actually prepends "hmacsha256=" to the payload BEFORE computing the HMAC.
 * This is NOT documented but is how their implementation works.
 *
 * Reference: https://linkedin-hookedin.vercel.app/LINKEDIN_WEBHOOK_SIGNATURE_VALIDATION.md
 */
function validateLinkedInSignature(payload, signature, clientSecret) {
  try {
    // If no signature provided, validation fails
    if (!signature) {
      console.warn('⚠️  No signature provided in X-LI-Signature header');
      return false;
    }

    // Strip the "hmacsha256=" prefix from the signature if present
    let signatureHash = signature;
    if (signature.startsWith('hmacsha256=')) {
      signatureHash = signature.substring(11); // Remove prefix
    }

    // CRITICAL: Prepend "hmacsha256=" to the payload before hashing
    // This is LinkedIn's actual implementation (undocumented)
    const SIGN_PREFIX = 'hmacsha256=';
    const stringToSign = SIGN_PREFIX + payload;

    // Compute the expected signature using HMAC-SHA256
    const hmac = crypto.createHmac('sha256', clientSecret);
    hmac.update(stringToSign, 'utf8');
    const expectedSignature = hmac.digest('hex');

    // Compare signatures (case-sensitive)
    const isValid = signatureHash === expectedSignature;

    if (!isValid) {
      console.error('⚠️  Signature mismatch:');
      console.error('   Expected:', expectedSignature);
      console.error('   Received:', signatureHash);
    }

    return isValid;

  } catch (error) {
    console.error('❌ Error validating signature:', error.message);
    return false;
  }
}

// =============================================================================
// START SERVER
// =============================================================================

app.listen(PORT, () => {
  console.log('');
  console.log('🚀 LinkedIn Webhook Server Started');
  console.log('=====================================');
  console.log(\`📡 Listening on port: \${PORT}\`);
  console.log(\`🔗 Webhook URL: http://localhost:\${PORT}/webhook\`);
  console.log(\`🔑 Client ID: \${CLIENT_ID}\`);
  console.log('');
  console.log('💡 To expose this server to the internet:');
  console.log('   Deploy to Vercel, Railway, Render, or similar platform');
  console.log('');
  console.log('⏳ Waiting for LinkedIn webhook events...');
  console.log('');
});

// Handle graceful shutdown
process.on('SIGINT', () => {
  console.log('\\n👋 Shutting down webhook server...');
  process.exit(0);
});
`;
  };

  const deploymentInstructions = `# Deployment Instructions

## Option 1: Deploy to Vercel (Recommended)

Vercel provides free hosting for Node.js applications and is perfect for webhook servers.

### Steps:

1. **Install Vercel CLI**
   \`\`\`bash
   npm install -g vercel
   \`\`\`

2. **Create a \`package.json\` file** in the same directory as \`server.js\`:
   \`\`\`json
   {
     "name": "linkedin-webhook-server",
     "version": "1.0.0",
     "main": "server.js",
     "scripts": {
       "start": "node server.js"
     },
     "dependencies": {
       "express": "^4.18.2"
     },
     "engines": {
       "node": "18.x"
     }
   }
   \`\`\`

3. **Create a \`vercel.json\` file** for configuration:
   \`\`\`json
   {
     "version": 2,
     "builds": [
       {
         "src": "server.js",
         "use": "@vercel/node"
       }
     ],
     "routes": [
       {
         "src": "/(.*)",
         "dest": "server.js"
       }
     ]
   }
   \`\`\`

4. **Deploy to Vercel**
   \`\`\`bash
   vercel
   \`\`\`

5. **Set Environment Variables** in Vercel Dashboard:
   - Go to your project settings
   - Add environment variables:
     - \`LINKEDIN_CLIENT_ID\`: Your LinkedIn client ID
     - \`LINKEDIN_CLIENT_SECRET\`: Your LinkedIn client secret

6. **Copy your Vercel URL** (e.g., https://your-app.vercel.app/webhook)

7. **Configure in LinkedIn Developer Portal**:
   - Go to your LinkedIn app
   - Navigate to Products > Webhooks
   - Paste your Vercel webhook URL
   - Save and verify

---

## Option 2: Deploy to Railway

Railway is another free hosting platform with simple deployment.

1. **Create account** at https://railway.app
2. **Click "New Project" > "Deploy from GitHub"**
3. **Connect your repository** or upload files
4. **Set environment variables**:
   - \`LINKEDIN_CLIENT_ID\`
   - \`LINKEDIN_CLIENT_SECRET\`
5. **Copy the generated URL** and configure in LinkedIn

---

## Option 3: Deploy to Render

1. **Create account** at https://render.com
2. **Click "New +" > "Web Service"**
3. **Connect repository** or upload files
4. **Configure**:
   - Build Command: \`npm install\`
   - Start Command: \`node server.js\`
5. **Add environment variables**
6. **Copy URL** and configure in LinkedIn

---

## Testing Locally (Development Only)

If you want to test locally first:

\`\`\`bash
# 1. Install dependencies
npm install express

# 2. Set environment variables (Mac/Linux)
export LINKEDIN_CLIENT_ID="your-client-id"
export LINKEDIN_CLIENT_SECRET="your-client-secret"

# 3. Run the server
node server.js

# Server will run on http://localhost:3000
\`\`\`

**Note**: LinkedIn webhooks require a public HTTPS URL, so local testing won't work for actual LinkedIn events. You must deploy to a hosting platform.
`;

  return (
    <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-8 mt-6">
      <div className="flex items-start justify-between mb-6">
        <div>
          <h2 className="text-2xl font-semibold text-gray-900 mb-2">
            💻 Code Generator
          </h2>
          <p className="text-gray-600">
            Generate a standalone Node.js webhook server with correct signature validation
          </p>
        </div>
      </div>

      {/* Generated Code */}
      <div className="mb-6">
        <div className="flex items-center justify-between mb-3">
          <h3 className="text-sm font-semibold text-gray-700">server.js</h3>
          <CopyButton text={generateServerCode()} />
        </div>
        <div className="bg-gray-900 text-gray-100 p-4 rounded-lg overflow-x-auto max-h-96 overflow-y-auto">
          <pre className="text-xs font-mono">
            <code>{generateServerCode()}</code>
          </pre>
        </div>
      </div>

      {/* How to Run Section */}
      <div className="bg-blue-50 border border-blue-200 rounded-lg p-5 mb-4">
        <h3 className="text-sm font-semibold text-blue-900 mb-3">
          📋 How to Run Locally
        </h3>
        <ol className="space-y-2 text-sm text-blue-800">
          <li>
            <strong>1.</strong> Save the code above as <code className="bg-blue-100 px-1.5 py-0.5 rounded">server.js</code>
          </li>
          <li>
            <strong>2.</strong> Install dependencies:
            <code className="block bg-blue-100 px-2 py-1 rounded mt-1 font-mono text-xs">
              npm install express
            </code>
          </li>
          <li>
            <strong>3.</strong> Set your LinkedIn client secret in the code (line 16) or use environment variables
          </li>
          <li>
            <strong>4.</strong> Run the server:
            <code className="block bg-blue-100 px-2 py-1 rounded mt-1 font-mono text-xs">
              node server.js
            </code>
          </li>
          <li>
            <strong>5.</strong> Server will run on <code className="bg-blue-100 px-1.5 py-0.5 rounded">http://localhost:3000/webhook</code>
          </li>
        </ol>
        <p className="text-xs text-blue-700 mt-3">
          ⚠️ Note: LinkedIn requires a public HTTPS URL. Local testing won't receive real LinkedIn events.
        </p>
      </div>

      {/* Deployment Instructions Toggle */}
      <button
        onClick={() => setShowInstructions(!showInstructions)}
        className="w-full flex items-center justify-between px-4 py-3 bg-gray-50 hover:bg-gray-100 border border-gray-200 rounded-lg transition-colors"
      >
        <span className="text-sm font-medium text-gray-700">
          📦 Deployment Instructions (Vercel, Railway, Render)
        </span>
        <span className="text-gray-400 text-sm">
          {showInstructions ? '▼' : '▶'}
        </span>
      </button>

      {/* Deployment Instructions Content */}
      {showInstructions && (
        <div className="mt-4 bg-gray-50 border border-gray-200 rounded-lg p-5">
          <div className="prose prose-sm max-w-none">
            <div className="bg-white p-4 rounded-lg overflow-x-auto max-h-96 overflow-y-auto">
              <pre className="text-xs font-mono whitespace-pre-wrap text-gray-800">
                {deploymentInstructions}
              </pre>
            </div>
          </div>
        </div>
      )}

      {/* Important Notes */}
      <div className="mt-6 bg-yellow-50 border border-yellow-200 rounded-lg p-4">
        <h4 className="text-sm font-semibold text-yellow-900 mb-2">
          ⚠️ Important Security Notes
        </h4>
        <ul className="space-y-1 text-sm text-yellow-800">
          <li>• <strong>Never commit your client secret to version control</strong> (use .env files and .gitignore)</li>
          <li>• <strong>Always use environment variables in production</strong></li>
          <li>• <strong>Keep your client secret secure</strong> - it's like a password</li>
          <li>• <strong>Use HTTPS in production</strong> - LinkedIn requires it for webhooks</li>
        </ul>
      </div>
    </div>
  );
}
